### PR TITLE
Show only one consolidate activity

### PR DESCRIPTION
**Pull request by indrora**
I'll let the commit message for 9142cdc5ba819a0cd12fdc95fb707cb2f6957f1d speak for itself: This fixes the second half of the bug described in #1077 enough that it looks right.

(now with rebase!)

### CODE REVIEW

**Comment by indrora** [comment]
Git got really confused about there being two commits between those histories. I'm unsure what git wizardly I'd need to properly summon the two together.

**Comment by dschuermann** [comment]
Could you exclude the changes in KeychainProvider.java and KeyListFragment.java? Then I would merge this directly.
KeyListFragment.java has this boilder plate code to allow us to see the snackbar with the log.

**Comment by indrora** [comment]
I'll see what I can do. If I don't touch KeyListFragment, the debug function still has the same problem. 

I *highly* suspect that somewhere, just somewhere, the Consolidate dialog is being popped from within the consolidation. I can't confirm this though. I'll take some time and find what's invoking the activity then.

**Comment by dschuermann** [comment]
@indrora Ah you are right :/

**Comment by indrora** [comment]
This task is a little above me, and this isn't a real fix for the problem.

Closing this PR.

**Pull request closed without merging**
