### PR TITLE
ISSUE #1304: Change keybase strings 

### PR DESCRIPTION
**Pull request by xSooDx**
-No longer appends the links to the keybase_narratives
-Now uses '%s' to insert the names in the keybase_narratives
-added '%s' to keybase_narrative_* in the string.xml file
-- NOTE:Have not modified for other languages

### CODE REVIEW

**Comment by Valodim** [comment]
the build failure is not your fault. no idea why that happens, rerun should fix it

**Comment by dschuermann** [comment]
@xSooDx Thanks for your pull request.
Is there a reason for using your own method "insertLinks()" instead of Android's formatting methods, described at http://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling ?

**Comment by xSooDx** [comment]
@dschuermann I did it because the i couldn't directly format a spannablestringbuilder without loosing the links in the string. string.format removed the links

**Comment by dschuermann** [comment]
@xSooDx Please rename the method to something like "formatSpannableString" and add a comment above the method why String.format cannot be used.

**Comment by timbray** [comment]
Why is the %s approach better?

**Comment by dschuermann** [comment]
@timbray In some languages the usernames are in the middle of a sentence and not at the end. The %s allows to have a dynamic position. See https://github.com/open-keychain/open-keychain/issues/1304

**Comment by xSooDx** [comment]
@dschuermann Made the changes you requested.

**Comment by dschuermann** [comment]
Great work

**Pull request merged**
