### PR TITLE
Fix for 1536

### PR DESCRIPTION
**Pull request by rohands**
#1536 
Tested by importing keys from PC

### CODE REVIEW

**Comment by rohands** [comment]
Why does it say some checks were unsuccessful?

**Comment by Valodim** [comment]
That's test coverage. It just means the ratio of tested vs untested lines decreased, so don't worry about it.

We're currently working on a release, will look at this PR after we're done with that :+1:

**Comment by rohands** [comment]
Sure sure.

**Comment by Valodim** [comment]
Looked this over, and I think it solves the actual problem at the wrong level. I'll put details in the related issue since it might require more discussion

**Pull request closed without merging**
