### PR TITLE
okhttp2 to okhttp3

### PR DESCRIPTION
**Pull request by kepuss**
Hi,

I've changed okhttp to version 3. Because in version 3 each client has its own connection pool I've made factory for okhttpclient. I also had to change  OkHttpKeybaseClient because UrlFactory is deprecated (which also needs change in KeybaseLib in other request)

### CODE REVIEW

**Comment by dschuermann** [comment]
@kepuss Please see my comments here: https://github.com/open-keychain/KeybaseLib/pull/1

After this I will resume reviewing and testing this pull request! :+1:

**Comment by kepuss** [comment]
Hi @dschuermann,
 I rebuilt KeybaseLib https://github.com/open-keychain/KeybaseLib/pull/2 and part form open-keychain. Please review :).

**Comment by dschuermann** [comment]
Thanks for your work on this! I did some fixes and merged it!

**Comment by kepuss** [comment]
@dschuermann, what issue can I do next? Do you have some crypto middle advanced (issues titles do not describe the level) ones? 

One more thing, have you and other members open-keychain reviewed the candidates for google SOC. I applied and I would like to know the status.

**Comment by dschuermann** [comment]
@kepuss We can provide any status about GSoC. The selected students will be announced on April 22, 2016

I don't know of crypto related issues which can be given to new contributors currently, sry.

**Comment by dschuermann** [comment]
@kepuss I found something for you which is crypto related :) see https://github.com/open-keychain/open-keychain/issues/1830

**Pull request merged**
