### PR TITLE
Add + button besides TokenAutoComplete, Issue #925

### PR DESCRIPTION
**Pull request by 007durgesh219**
screenshot_20160405-233757

### CODE REVIEW

**Comment by dschuermann** [comment]
Nice, I actually like this approach, much less intrusive than having a fullscreen activity.

@Valodim what do you think?

**Comment by Valodim** [comment]
Yup looks good. I'm not fond of the more narrow dropdown though, can you change the dropdown anchor view to extend to the right in width?

**Comment by 007durgesh219** [comment]
Sure, I will update PR soon

**Comment by 007durgesh219** [comment]
I've updated PR. Now it will look like this:
screenshot_20160414-023059

@Valodim We can make it look like this also. No margin on left and right
screenshot_20160414-022442

Which one is more sutaible according to you??

**Comment by dschuermann** [comment]
Nice solution and great work. I adapted it a little bit to only expand the width to include the add button.

**Comment by dschuermann** [comment]
Reverted with https://github.com/open-keychain/open-keychain/commit/f44bd236224e782d85c9764a4b655ae922356b14 due to https://github.com/open-keychain/open-keychain/issues/1857

**Pull request merged**
