### PR TITLE
Add adaptive icons

### PR DESCRIPTION
**Pull request by kowalski7cc**
## Description
Add support for adaptive icons in devices running API 26 or Greater

## Motivation and Context
Uniform icon look and feel with updated Android look among other apps.

## How Has This Been Tested?
Made with android studio, tested on Nexus with Pixel Launcher

## Screenshots (if appropriate):
image
image

## Types of changes
- ✅ Vector logo to support any DPI (yeah, i love pushing pixels!)
- ✅ Support for Android adaptive icons
- ✅ Support for round only icon view (API 25)
- ✅ Keep legacy icon for <=API 25 for feel consistency in older Android versions
- ✅ Support for blue debug adaptive icon with same behaviour of the release icon

### CODE REVIEW

**Comment by lokesh-krishna** [comment]
Wonderful work! :grin:

**Comment by ArchangeGabriel** [comment]
Still missing some shadows for me.

**Comment by kowalski7cc** [comment]
Issue is that if the icon moves, you risk that moving the shadow it should show a white space

**Comment by Valodim** [comment]
Hmh. So we've been thinking and it's hard to put a finger on it but we're not really happy yet. The key looks plain, but not in the "nice plain" way like the NFC one in your screenshot. Maybe a shadow? Or keeping the ring and putting a hole in the background? Not sure :question:

**Comment by kowalski7cc** [comment]
I'll try remake it and see what comes out

Il mar 29 mag 2018, 12:38 Vincent Breitmoser <notifications@github.com> ha
scritto:

**Comment by ArchangeGabriel** [comment]
@kowalski7cc I don’t understand your issue with “if the icon moves”. But a shadow is definitively what is missing for me, it’s what makes the `Reward` and `Presentazi..` icons look way better in my opinion.

**Comment by kowalski7cc** [comment]
Something like this?
image

**Comment by ArchangeGabriel** [comment]
Way better! There is a bit of inconsistency with the missing shadow in the keyhole, but other than that I like it. :)

**Comment by Valodim** [comment]
Looks good! :+1: Can you update the pr for the one with the shadow? Besides the shadow, the orientation of the key also solves the problem for me that the diagonal line "divided" the key into two parts.  I also found that I like even the current PR better in live on the phone than statically in the picture here, so that's good.

**Comment by Valodim** [comment]
@kowalski7cc Any chance you could update the PR with the new shadowy icon? :)

**Comment by kowalski7cc** [comment]
Here I am, sorry for make you waiting ;)
Is this good:
ic_launcher_round
Preserving old icon for older devices and prividing round icon:
image
Debug on phone:
image

**Comment by Valodim** [comment]
I like it. I notice the hole in the key is now darkened. I thing I like it, but was there any particular reasoning behind this?

**Comment by ArchangeGabriel** [comment]
@Valodim Yes, see my previous comment. ;)

**Pull request closed without merging**
