### PR TITLE
WIP: Add Nitrokey support

### PR DESCRIPTION
**Pull request by dschuermann**
Currently I get
```
AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 1924
  1924         AndroidRuntime  E  java.lang.RuntimeException: An error occured while executing doInBackground()
  1924         AndroidRuntime  E  at android.os.AsyncTask$3.done(AsyncTask.java:304)
  1924         AndroidRuntime  E  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
  1924         AndroidRuntime  E  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
  1924         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  1924         AndroidRuntime  E  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
  1924         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  1924         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  1924         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)
  1924         AndroidRuntime  E  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 688448510 byte allocation with 16777216 free bytes and 166MB until OOM
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.securitytoken.UsbTransport.receive(UsbTransport.java:255)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.securitytoken.UsbTransport.setIccPower(UsbTransport.java:82)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.securitytoken.UsbTransport.connect(UsbTransport.java:192)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.connectToDevice(SecurityTokenHelper.java:150)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity.handleSecurityToken(BaseSecurityTokenNfcActivity.java:412)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity$1.doInBackground(BaseSecurityTokenNfcActivity.java:171)
  1924         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity$1.doInBackground(BaseSecurityTokenNfcActivity.java:161)
  1924         AndroidRuntime  E  at android.os.AsyncTask$2.call(AsyncTask.java:292)
  1924         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  1924         AndroidRuntime  E  ... 4 more
```

### CODE REVIEW

**Comment by dschuermann** [comment]
@nmikhailov

**Comment by nmikhailov** [comment]
I will be able check everything once I will receive my Nitrokey. ETA  2 weeks+

**Comment by nmikhailov** [comment]
Judging from frimware sources Nitrokey Start and Nitrokey Pro are different devices. 
Nitrokey Start's frimware is based on gnuk and implements T=1; short APDU level of exchange, while Nitrokey Pro is T=1; TPDU level of exchange.  (@jans23 could you confirm?)

We have currently support for 'short and extended APDU' which is what yubikey provides. But we don't use extended apdus afaik. So Nitrokey Start should theoreticaly work, but I don't have one to test(I only have Nitrokey Pro).

**Comment by jans23** [comment]
AFAIK APDU and TPDU are different layers and based on each other. I think they aren't alternatives. Hence, I don't get your question.

I tested the latest OpenKeychain with Nitrokey Pro and Start using a blank installation. The wizard starts where I select "security token". On the next screen I'm asked to connect a device but none of them is recognized. Is it supposed to recognize the Nitrokey at this step or does it work differently?

**Comment by nmikhailov** [comment]
@jans23 APDU and TPDU are different layers indeed, but I was talking about CCID's level of exchange.
CCID sets it in dwFeatures, Nitrokey Pro has TPDU level of exchange which means that we need to pack APDU in TPDU frame in OpenKeychain. 
Nitrokey Start has short APDU level of exchange which mean that we should send APDU's and they will be wrapped in TPDU Frame by CCID and send to ICC

My point is that from my perspective these are very different devices.

You can't test it yet since Nitrokeys are not whitelisted as they don't work yet. Although I think that Nitrokey Start should mostly work with current implementation.

**Comment by jans23** [comment]
@nmikhailov Are you talking about Extended Length? Yes, I can confirm that Nitrokey Pro uses that.

**Comment by nmikhailov** [comment]
Well my main point is that we shouldn't add 'start' to whitelist on the basis that 'pro' version works. And I have only 'pro' version.

**Comment by nmikhailov** [comment]
@dschuermann is it legal to add files from OpenJDK to the project? For example something like this: http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/f51368baecd9/src/share/classes/javax/smartcardio/CommandAPDU.java

**Comment by dschuermann** [comment]
@nmikhailov Yes that's legal, since the OpenJDK is GPLv2 and we are GPLv3.
I am in favor of reusing existing code from the javax.smartcardio API, but does it really makes sense to use the full API?

**Comment by nmikhailov** [comment]
@dschuermann I have been thinking moving otg stuff to a lib to allow future reuse, but that would require creating a good public api. But now I think I can just take the api from smatcardio and add android specific stuff and protocol handling instead of pc/sc calls. This means that the lib will provide well designed & well known general purpose apis. And the issues like this(eg card reader/icc support) will be worked on mostly in that lib.

**Comment by dschuermann** [comment]
Sounds great but also like a lot of work ;) Depends on your free time...

**Comment by jans23** [comment]
@nmikhailov I can send you a Nitrokey Start for testing. Please send me your postal address again.

**Comment by dschuermann** [comment]
See new pr: https://github.com/open-keychain/open-keychain/issues/1868

**Comment by jans23** [comment]
@nmikhailov Did the Nitrokey Start arrive?

**Comment by nmikhailov** [comment]
@jans23 Yes, I have received a post notice today, will pick up this week, thanks.

**Comment by nmikhailov** [comment]
@jans23 received it and checked with OKC. It didn't worked straight away, so its a good thing that you have sent it.

**Comment by 41px** [comment]
No new for the NitroKey Pro ?

**Comment by nmikhailov** [comment]
@41px I am working on it in #1868 Nitrokey Pro support is done, but PR is not.

**Comment by 41px** [comment]
@nmikhailov thx.

**Pull request closed without merging**
