### PR TITLE
WIP: simplified internal mime parsing

### PR DESCRIPTION
**Pull request by dschuermann**
Work in progress

not finished...

The idea is to get the content in GMail with an app using an accessibility service, e.g. screenreader and then send this content to OK for MIME parsing.

### CODE REVIEW

**Comment by alanthehat** [comment]
This? -- https://en.m.wikipedia.org/wiki/S/MIME

**Comment by dschuermann** [comment]
@alanthehat Nope, PGP/MIME

**Comment by Valodim** [comment]
It's actually not even PGP/MIME, it's just MIME :)

**Comment by alanthehat** [comment]
Can I dare hope for RFC3156?
To my understanding this 14 year old document has become the de-facto standard everywhere apart from Android. 
I assume that this will only decrypt incoming mail & we are still waiting for mailer software to implement sending?

**Comment by dschuermann** [comment]
@alanthehat This PR is only for parsing content from the GMail Android app. If the GMail app can't handle the MIME content it just displays it, thus "application/octet-stream" is displayed inside GMail. We could get this via a accessibility service, give it to OpenKeychain, decrypt it, and then parse the MIME content via this pr.

Real PGP/MIME support must be implemented in an open source email app, such as K-9 Mail. From OpenKeychain's side, everything that is needed for this is already available via our API.

**Comment by alanthehat** [comment]
Such as this from 2013? -- https://code.google.com/p/k9mail/issues/detail?id=5864 
There seem to have been several complete & working solutions offered, but none have been included :-(

**Comment by dschuermann** [comment]
The current git master of K-9 Mail contains "work in progress" code. Please discuss everything related to k-9 in their bug tracker/mailinglist

**Comment by Valodim** [comment]
started working on this on the side

**Comment by Valodim** [comment]
this sort-of works now.

the context menu isn't done yet, and I'm not sure how to layout this - the show log and delete file operations belong to the "container" rather than the individual items, while "share" and "save" belong to the items. will have to think about this some more..

the operation itself is also not nearly as well tested as it should be, particularly for error scenarios (including non-mime content). it also doesn't support multipart/signed mime structures, only encrypt+signed data with mime content.

I'm also expecting some issues with the way content types are handled: mime4j defaults to "text/plain" if no content type is specified. could be troublesome.

**Comment by alanthehat** [comment]
Thank you hugely for this. It sounds like it will finally make PGP/MIME usable in Android :-D

**Comment by dschuermann** [comment]
I tried one freshly MIME encrypted mail sent with enigmail, but it fails:
```
  766          PackageManager  I  Setting last chosen activity org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity for user 0:
  766          PackageManager  I  Type: "text/plain"
  766         ActivityManager  I  START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.attachmentprovider/9ec30512-31af-4a8e-98df-0cb88570ceb3/1699/VIEW typ=text/plain flg=0x13080001 cmp=org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity} from uid 10104 on display 0
  766           WindowManager  V  addAppToken: AppWindowToken{19c0f7ca token=Token{2609d735 ActivityRecord{1234356c u0 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity t3279}}} to stack=1 task=3279 at 0
  766           WindowManager  V  Adding window Window{2a9ab7ed u0 Starting org.sufficientlysecure.keychain.debug} at 20 of 26 (after Window{2b1c757d u0 android/com.android.internal.app.ResolverActivity})
 13211             Keychain D  D  mInputUri=content://com.fsck.k9.attachmentprovider/9ec30512-31af-4a8e-98df-0cb88570ceb3/1699/VIEW
  766           WindowManager  V  Adding window Window{3350126e u0 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity} at 20 of 27 (before Window{2a9ab7ed u0 Starting org.sufficientlysecure.keychain.debug})
 13211               Timeline  I  Timeline: Activity_idle id: android.os.BinderProxy@2f4138a4 time:34455170
 13211             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_DATA, mParameters=null, mIndent=0}
 13211             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_DATA_OPENPGP, mParameters=null, mIndent=1}
 13211             Keychain D  E  File creation failed!
 13211             Keychain D  D  ASCII Armor Header Line: -É<ï|É(ðUÉÝÁU<"¿¹Í©é¥
 13211             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_DC, mParameters=null, mIndent=0}
 13211             Keychain D  D  Send message by setProgress with progress=0, max=100
 13211             Keychain D  D  data error
 13211             Keychain D  D  java.lang.ArrayIndexOutOfBoundsException: length=128; index=243
 13211             Keychain D  D  at org.spongycastle.bcpg.ArmoredInputStream.decode(ArmoredInputStream.java:86)
 13211             Keychain D  D  at org.spongycastle.bcpg.ArmoredInputStream.read(ArmoredInputStream.java:451)
 13211             Keychain D  D  at org.spongycastle.bcpg.BCPGInputStream.nextPacketTag(BCPGInputStream.java:114)
 13211             Keychain D  D  at org.spongycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:101)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.pgp.PgpDecryptVerifyOperation.decryptVerify(PgpDecryptVerifyOperation.java:379)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.pgp.PgpDecryptVerifyOperation.executeInternal(PgpDecryptVerifyOperation.java:163)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.pgp.PgpDecryptVerifyOperation.execute(PgpDecryptVerifyOperation.java:123)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.operations.InputDataOperation.execute(InputDataOperation.java:88)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.operations.InputDataOperation.execute(InputDataOperation.java:55)
 13211             Keychain D  D  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:140)
 13211             Keychain D  D  at java.lang.Thread.run(Thread.java:818)
 13211             Keychain D  V  log: LogEntryParcel{mLevel=ERROR, mType=MSG_DC_ERROR_IO, mParameters=null, mIndent=1}
 13211             Keychain D  V  log: LogEntryParcel{mLevel=ERROR, mType=MSG_DATA_ERROR_OPENPGP, mParameters=null, mIndent=1}
  766         ActivityManager  I  Displayed org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity: +132ms
 13211             Keychain D  D  Handling result in OperationHelper success: false
  766                Timeline  I  Timeline: Activity_windows_visible id: ActivityRecord{1234356c u0 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity t3279} time:34455876
  766         ActivityManager  W  Finishing task with all activities already finished
```

**Comment by dschuermann** [comment]
Need to press "download complete message" in K-9 before opening attachment -> k9 bug :(

**Comment by dschuermann** [comment]
BTW: the log " 13211             Keychain D  E  File creation failed!" is confusing...

**Comment by Valodim** [comment]
- non-mime content done
- moved context menu to top right of card, and share/save/open-with into a bottom sheet on long-click of items
- added charset handling

Besides some minor cosmetic changes, I think we can merge this. Finally, a workable workaround for pgp/mime for the time being =)

**Comment by Valodim** [comment]
what's missing still is support for sign-then-encrypt, i.e. http://tools.ietf.org/html/rfc3156#section-6.1

this is a bit complicated, roughly:
1. decryption of the message
2. mime-parsing of decrypted data
3. if a multipart/signed is encountered, flat-parsing of the signed data and the signature
4. verification of the signature, and merging the signature result into the existing decryption result
5. recursive mime-parsing of the signed data
6. ignore w/ warning of any following mime parts

at the moment, we just do 1+5, which is enough for signed+encrypted data with mime content

**Comment by dschuermann** [comment]
If I execute "open with" on text/plain it still only opens our internal viewer. Would be nice if the other text/plain viewers can be selected there.

**Comment by Valodim** [comment]
using chooser intent for everything now except single click on a text/plain item

**Comment by Valodim** [comment]
I noticed evolution uses sign-then-encrypt by default, so we do need support for that - aand it's done.

Pretty happy with this branch now, gonna merge tomorrow if nothing important comes up.

**Pull request merged**
