### PR TITLE
WIP: Switch to RecyclerViews

### PR DESCRIPTION
**Pull request by tobsbot**
Relates to #1052: 

Since RecyclerView is now the recommended (and more efficient way) to display lists of items,
ListViews parts of the ui should be ported to it.

Activities / Fragments ported:
- [x] ViewKeyAdvCertsFragment
- [x] LogDisplayFragment
- [x] SelectPublicKeyFragment
- [x] SelectSignKeyIdListFragment

### CODE REVIEW

**Comment by dschuermann** [comment]
Code looks good for the start. Looking forward to your upcoming changes!

**Comment by dschuermann** [comment]
Great progress!

**Comment by Valodim** [comment]
Wow this is a very large PR. Can you do me a huge favor and split the keylist part out from the other places where you switched to RecyclerView? Should be possible by just reverting to master for the relevant files. That would be tremendously helpful for review :+1:

**Comment by Valodim** [comment]
Great!

Also I compiled and ran the PR some time yesterday, and I couldn't open the KeyView activity from the key list:

```
mDataUri: content://org.sufficientlysecure.keychain.debug.provider/key_rings/-1
query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/-1/public, proj=[key_ring_data])
Query: SELECT key_ring_data FROM keyrings_public WHERE (master_key_id = '-1')
key not found!
org.sufficientlysecure.keychain.provider.ProviderHelper$NotFoundException
at org.sufficientlysecure.keychain.provider.ProviderHelper.getGenericData(ProviderHelper.java:199)
at org.sufficientlysecure.keychain.provider.ProviderHelper.getGenericData(ProviderHelper.java:152)
at org.sufficientlysecure.keychain.util.NfcHelper$3.doInBackground(NfcHelper.java:131)
at org.sufficientlysecure.keychain.util.NfcHelper$3.doInBackground(NfcHelper.java:126)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by dschuermann** [comment]
Hey @tobsbot . Again sorry for the delay. I pulled your changes into https://github.com/open-keychain/open-keychain/tree/tobsbot-recycler-view

There is still a problem with ``SelectSignKeyAdapter``. To reproduce: In an app that uses OpenKeychain's API such as "Password Store" go to Settings -> Select OpenPGP Provider, select OpenKeychain, then in click on "Select key" and grant access. OpenKeychain will now crash with

```
 AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 27109
 27109         AndroidRuntime  E  java.lang.IllegalStateException: Couldn't move cursor from position: -1 to position: -1!
 27109         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.util.adapter.CursorAdapter.moveCursorOrThrow(CursorAdapter.java:179)
 27109         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.KeyCursorAdapter.onBindViewHolder(KeyCursorAdapter.java:36)
 27109         AndroidRuntime  E  at org.sufficientlysecure.keychain.remote.ui.adapter.SelectSignKeyAdapter.onBindViewHolder(SelectSignKeyAdapter.java:76)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6062)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6095)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5277)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
 27109         AndroidRuntime  E  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
 27109         AndroidRuntime  E  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
 27109         AndroidRuntime  E  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
 27109         AndroidRuntime  E  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
 27109         AndroidRuntime  E  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
 27109         AndroidRuntime  E  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
 27109         AndroidRuntime  E  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
 27109         AndroidRuntime  E  at android.view.View.layout(View.java:15686)
 27109         AndroidRuntime  E  at android.view.ViewGroup.layout(ViewGroup.java:5039)
 27109         AndroidRuntime  E  at android.view.ViewRootImpl.performLayout(ViewRootImpl.ja
```

**Pull request closed without merging**
