### PR TITLE
Fix pulling Serbian translation from Transifex

### PR DESCRIPTION
**Pull request by pejakm**
[History review of translation file for Serbian language](https://github.com/open-keychain/open-keychain/commits/master/OpenKeychain/src/main/res/values-sr/strings.xml) shows that Serbian translations aren't updated since February 28th. This should fix things.

##### Changes #####

* added `sr: sr` to the `lang_map` array
* removed `sr_CS: sr-rCS` from `lang_map` array (it's deprecated long ago)

### CODE REVIEW

**Comment by dschuermann** [comment]
thanks!

**Comment by dschuermann** [comment]
Hmm, I am not sure this is the real problem here. sr: sr shouldn't be necessary in this map as it should come automatically with the transifex tool. de: de is also not included for example.
I think it's more this problem: https://github.com/open-keychain/open-keychain/issues/1128

**Comment by dschuermann** [comment]
@pejakm Sry, but I reverted your commit. It is definitly #1128

**Comment by pejakm** [comment]
Oh, sorry, I wasn't aware of this. Is there a way to figure out which character causes this? (Although I'm suspecting on `ô`.)

**Comment by dschuermann** [comment]
@pejakm np. I am not sure, I think someone needs to debug transifex-client.

**Pull request merged**
