### PR TITLE
EmailEditText, PasswordEditText issue #1106

### PR DESCRIPTION
**Pull request by chipset95**
Created EmailEditText extending AutoCompleteTextView with TextWatcher to validate email.
Created PasswordEditeText extending EditText with TextWatcher & Wrapper for PasswordStrengthView.
Implemented them in CreateKeyInputFragment, AddUserIdDialogFragment, SetPassphraseDialogFragment along with required XML changes.
All done in accordance with issue #1106 

EmaiEditText with Suggestions
PasswordEditText with passphrase strength indicator
PasswordEditText with passphrase strength indicator in SetPassphraseDialogFragment
EmaiEditText with Suggestions in AddUserIdDialogFragment

### CODE REVIEW

**Comment by dschuermann** [comment]
Looks great!
Please add the GPLv3 license header like done in all other OpenKeychain classes.

**Comment by chipset95** [comment]
Added in commit [7c2fefe](https://github.com/chipset95/open-keychain/commit/7c2fefe2f7b9f6f7d770e37041336ae563518e93)

**Comment by Valodim** [comment]
from a quick glance this code crashes with a nullpointer if a PasswordEditText is changed without having a passwordstrengthview associated to it. Is there a reason PasswordStrenthView isn't just integrated with PasswordEditText? As it is, PasswordEditText is just an EditText with a (non-optional) afterTextChanged Listener but doesn't really add functionality of its own...

codestyle notes: fields don't have an m prefix, local variables should positively never have an m prefix.

**Comment by dschuermann** [comment]
@Valodim np, I merged too fast :/ should have left the PR open. My fault

**Comment by chipset95** [comment]
@Valodim `PasswordStrengthView` doesn't have any code of its own in the mentioned fragments. All we have to do is create the corresponding xml in the layout, reference it in java and attach the `EditText` to it.

I could check for null and prevent the crash, or get the logic of `PasswordStrengthView` to `PasswordEditText` itself. I believe checking for null would be better because if in future a `PasswordEditText` without the strength indicator is needed, it'll be easier this way.

**Comment by adithyaphilip** [comment]
I happened to have created a standalone PassphraseEditText for my earlier PR (https://github.com/open-keychain/open-keychain/pull/1075). I've raised a new PR for it at https://github.com/open-keychain/open-keychain/pull/1111
I guess that would solve the issue raised by @Valodim ?

**Pull request merged**
