### PR TITLE
[WIP] Support for GNUK and Nitrokey Start

### PR DESCRIPTION
**Pull request by nmikhailov**
There are some difficulties with GNUK:
- can't be rested to default - in fact our procedure will most likely brick it
- keys can't be overriden(there is a tool to remove keys with admin PIN in gnuk sources, but I think that it out of scope for us)
- Some weird admin-less mode which messes our token initialization routine.
- [x] fix sign/decrypt
- [ ] fix(or disable) token initialisation for gnuk
- [ ] disable key move if its gnuk
- [ ] disable token reset if its gnuk

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi @nmikhailov !
How is it going with the PR? Could I help with testing?

**Comment by Valodim** [comment]
Can you say more on why the GNUK can't be reset to defaults? Isn't that standard behavior of the javacard applet?

**Comment by nmikhailov** [comment]
@Valodim GNUK is not javacard, its a firmware for microcontroller written in C.

**Comment by jans23** [comment]
Gnuk 1.2 can be reset to factory defaults. Earlier Nitrokey Start can be updated to Gnuk 1.2 too.

**Comment by jeremydrake-eAc** [comment]
It sounds like [Gnuk 1.2.5](https://anonscm.debian.org/cgit/gnuk/gnuk/gnuk.git/commit/?h=release/1.2.5&id=83414a747ae8f09639ecaf1d9a8c7e3988068c0f) fixed how it handles reset, so your token reset code should work with Gnuk 1.2.5 and later.

I don't really understand the other issues - can you explain more about what's wrong with token initialization, and what you mean by "key move"?

**Comment by jeremydrake-eAc** [comment]
OK, I got the current master branch and merged these changes, and was able to confirm that token reset does work against Gnuk 1.2.5, however setting up a blank token fails.  I added logging to output every APDU transmitted and every response, and here is where it went wrong:
`V/Keychain D( 7100): Sending APDU {00da00c106010800001103}`
`V/Keychain D( 7100): Received APDU {6f00}`

Gnuk expects the algorithm attributes for RSA 2048 to be `06010800002000`, the differences being that the exponent should sent as a 32-bit value (despite still having the value 65537), and that it expects the 'standard' format rather than the 'crt with modulus' format.

**Comment by dschuermann** [comment]
This pull request is superseded by https://github.com/open-keychain/open-keychain/pull/2201

@jeremydrake-eAc Thanks a lot for this detailed debugging information. This helped us a lot to fix GNUK issues ❤️

**Pull request closed without merging**
