### PR TITLE
Changed drawable resources to Material - issue #1048

### PR DESCRIPTION
**Pull request by chipset95**
Replaced some of the holo drawables with Material Design icons taken from https://google.github.io/material-design-icons/ as mentioned in issue #1048 

I was not able to use the provided scripts, but I managed to get most of the icons with correct sizes.

### CODE REVIEW

**Comment by chipset95** [comment]
Missed one drawable, added it in commit 739917b

**Comment by dschuermann** [comment]
* Why wasn't you able to use the script?
* Please use the original names of the icons
* Choose fitting icons not just by name

**Comment by chipset95** [comment]
&bull; I ran the script but it gave me `missing res dir` with the res path of the app in the options.json files's basepath. Any help in usage of the the scripts would be appreciated.
&bull; I kept the file names same as those of holo, so that they won't have to be changed wherever they were referenced
&bull; I manualy matched the image with its purposes so that they don't loook out of place.

**Comment by chipset95** [comment]
Just fixed a file name in the latest commit [3496a22](https://github.com/chipset95/open-keychain/commit/3496a22468eec62b3eba984584255bbc82168358)

**Comment by dschuermann** [comment]
* Not sure why the script does not work. Are you using something different than Linux?
* Please use original file names
* Please use icons with "keys" instead of "people". (Also look at http://materialdesignicons.com/ for key icons)

**Comment by dschuermann** [comment]
Done in https://github.com/open-keychain/open-keychain/pull/1090

**Pull request closed without merging**
