### PR TITLE
Fix for NFC signing operations: move PIN verify inside sign/decrypt operation and set correct mode.

### PR DESCRIPTION
**Pull request by josecastillo**
According to the OpenPGP spec, PW1 must be submitted with mode 81 for a signing operation, and mode 82 for everything else. OpenKeychain currently verifies the PW1 with mode 82 all the time. OpenPGP-compliant cards will not issue a signature when the PW1 is submitted with mode 82. 

The reason this hasn't been broken is that the only widespread OpenPGP device with NFC, the Yubikey NEO, had a bug that allowed signatures to be generated without a verified PIN. Yubico has fixed this bug as of today, and issued [a security advisory](https://github.com/Yubico/ykneo-openpgp/blob/master/doc/SecurityAdvisory%202015-04-14.txt). New Yubikeys NEO will throw an error when signing is attempted after VERIFY PW1 with mode 82. 

This patch moves the PIN verification from the ```handleNdefDiscoveredIntent``` into a new method called ```nfcVerifyPIN```, which takes as a parameter the mode of operation. The new method is called from the sign and decrypt methods, so that the PIN can be submitted with the proper mode for the requested operation. If the PIN verification fails, an IOException is thrown, which is caught and passed to ```handleNfcError```. 

I've tested this on a Nexus 7, which is the only NFC-equipped Android device I have on hand, but I would welcome additional testing.

### CODE REVIEW

**Comment by dschuermann** [comment]
Thanks for investigating and actually fixing it also on our side!

**Comment by Valodim** [comment]
Thanks for the fix! Seems I missed that part of the spec completely...

Do you happen to have some timing information on the VERIFY call? More specifically, is it worth keeping an expected state, or does the VERIFY operation take negligible time? Depending on the operation done, there may be several nfcCalculateSignature calls and we could avoid subsequent VERIFYs for those

**Comment by josecastillo** [comment]
The verify call is pretty negligible in terms of overhead; I just ran a few tests and found the verify operation taking ~0.09 seconds, compared to ~.64 seconds for a decrypt operation with a 2048-bit key. Still, it might make sense to track the state if only to avoid spamming the PIN over the NFC interface. 

I'd be more than willing to take a crack at implementing this; I'm very familiar with the smart card specification at this point, and I'm actually working on an NFC OpenPGP smart card so it's quite relevant to my current work.

**Comment by dschuermann** [comment]
@josecastillo Contribtions in that area are more than welcome, so if you would like to work on improving the NFC stuff, awesome!
If you have any questions while implementing don't hesitate to ask here via issues or via our mailinglist at http://groups.google.com/d/forum/openpgp-keychain-dev

**Pull request merged**
