### PR TITLE
Fixed expiry change crash(for Android L as well)

### PR DESCRIPTION
**Pull request by montimaj**
@dschuermann  Hopefully I have fixed this issue #1059  this time. If an invalid date is selected then the expiry date is set to the previous expiry date.
case1
//invalid date
case2
If an invalid date is selected then last expiry date is set.
case1

### CODE REVIEW

**Comment by dschuermann** [comment]
After thinking about it, I would like to see the following:
If the user clicks on a date (DatePicker.OnDateChangedListener) that should be normally be disabled (but is _not_ due to the mentioned bug in Android 5), the date picker should reset itself to the old expiry date and show a Toast that this date should not be selected.

**Comment by montimaj** [comment]
Ok got it the Toast part is left!

**Comment by montimaj** [comment]
Hope this is what you suggested :) 
case3
case4
case5

**Comment by dschuermann** [comment]
Can you do this in DatePicker.OnDateChangedListener?

**Comment by montimaj** [comment]
Ok

**Comment by dschuermann** [comment]
Even better: after clicking on a "disabled" date just hop back to the last selected date and show toast.

**Comment by dschuermann** [comment]
The crash still happens but I was able to get the old spinner back (which in this case makes more sense than the big calendar view): https://github.com/open-keychain/open-keychain/commit/be06c4cd5839d9860485fc96e152794c68484e71

**Comment by dschuermann** [comment]
One last remark for @montimaj : If you still want to work on that issue, please think about the purpose of the code before trying again.

**Pull request closed without merging**
