### PR TITLE
Passphrase strength indicator

### PR DESCRIPTION
**Pull request by adithyaphilip**
Refers to Issue https://github.com/open-keychain/open-keychain/issues/1050

Passphrase Strength Indicator added in CreateKeyInputFragemnt, below the passphrase EditText and above the passphrase verify EditText.

Looks like:
screenshot_2015-03-03-01-23-30

### CODE REVIEW

**Comment by dschuermann** [comment]
Thanks for your effort.
* Please add the text from https://github.com/matt-allen/android-password-strength-indicator/blob/master/LICENSE to the files from the project. Similar to the headers in our class files.
* Please change the implementation that it uses our colors.

**Comment by dschuermann** [comment]
Thinking about this further, it would be perfect to have the password meter integrated on the right side. Similar to what Twitter does on https://twitter.com/signup
This would make it less annoying and similar to what we do for the email field.

**Comment by adithyaphilip** [comment]
I've changed the colors, and embedded the progress indicator in the EditText, as Twitter does. 
screenshot_2015-03-04-03-16-58
screenshot_2015-03-04-03-17-07
screenshot_2015-03-04-03-17-14
I wasn't sure if we should use absolute dp to specify the width and height of the progress indicator, so I made it cover 20% of the width of the EditText. However, this resulted in quite a bit of nesting in the xml layout, is there a better way to go about it?
Also, the passphrase might end up going behind the indicator if it's too  (extremely) long, would an implementation like below be more appropriate?
screenshot_2015-03-04-02-50-46

**Comment by lezorich** [comment]
Hi, I didn't noticed that @adithyaphilip has this PR, I also worked on this patch. @adithyaphilip for the passphrase not going behind the indicator you can set padding on the edit text :) [Here](https://lh3.googleusercontent.com/-khxh3oS7SvQ/VPYvGlLgViI/AAAAAAAADhs/H65pR-q7aO4/w319-h567-no/Screenshot_2015-03-03-18-51-36.png) is my working branch for you to see how I did it (you did the PR first, so the issue is yours :p).

I thought that something like this looks nice:
![Image weak passphrasr]
(https://lh5.googleusercontent.com/-DvKQ7JlT1oE/VPYvH7OBgxI/AAAAAAAADh4/C_av353wuSQ/w319-h567-no/Screenshot_2015-03-03-18-50-59.png)

![Image medium passphrase]
(https://lh3.googleusercontent.com/-eiHntHlTezM/VPYvJAq-nLI/AAAAAAAADiE/TACy1aaO_dI/w319-h567-no/Screenshot_2015-03-03-18-51-18.png)

![Image strong passphrase]
(https://lh3.googleusercontent.com/-khxh3oS7SvQ/VPYvGlLgViI/AAAAAAAADhs/H65pR-q7aO4/w319-h567-no/Screenshot_2015-03-03-18-51-36.png)

**Comment by dschuermann** [comment]
Looks already great, nice effort, @adithyaphilip and @lezorich 

* Use padding as @lezorich suggested
* Also add into SetPassphraseDialogFragment

**Comment by Valodim** [comment]
wouldn't this be better placed in a standalone PassphraseEditText widget which extends EditText?

**Comment by dschuermann** [comment]
@Valodim great idea!

**Comment by dschuermann** [comment]
Thanks for your efforts @lezorich and @adithyaphilip . This counts as a patch to both of you! I merged the codebase of @lezorich because it was more ready and added a new issue here: https://github.com/open-keychain/open-keychain/issues/1106 .

**Pull request closed without merging**
