### PR TITLE
Fixed expiry change crash

### PR DESCRIPTION
**Pull request by montimaj**
Issue #1059  has been successfully resolved.

### CODE REVIEW

**Comment by montimaj** [comment]
@dschuermann The calender does not  allow the user to select any invalid date. So is there any use of 'numDays' at all? The crash can also be fixed simply removing the block if(numDays<=0) {...

**Comment by dschuermann** [comment]
Obviously it somehow is possible to get numDays = 0....

**Comment by montimaj** [comment]
So is there anything more to be done here? I think the issue is fixed.

**Comment by dschuermann** [comment]
We don't want the user to select anything that results in an expiry date before today.

**Comment by montimaj** [comment]
The calendar won't allow it 
screenshot_2015-03-03-17-33-12
screenshot_2015-03-03-17-33-37

**Comment by dschuermann** [comment]
This is why we had this if clause there. This should not happen. Unfortunatly it looks Android 5 again allows having older dates selected in the widget.

**Comment by dschuermann** [comment]
http://stackoverflow.com/questions/28085786/fix-datepickerdialog-setmaxdate-and-setmindate-on-android-lollipop

**Comment by dschuermann** [comment]
Looks like we need to check on our own and inform the user about this.

**Comment by Valodim** [comment]
@montimaj Sorry to say this, but your approach to this issue was *completely* wrong.

The check is there to make sure the variable stays in its expected domain. For good reason obviously, because with an update of android values outside this domain did in fact happen. Removing it is not only not the right solution here, but the way you initially did it (catching a runtimeexception right after it was thrown) makes no sense.

We appreciate your effort, but the goal here should be to get the actual issues fixed, not just remove a symptom and get a pull request accepted quickly.

**Pull request closed without merging**
