### PR TITLE
WIP: Save split user ids in database #1745

### PR DESCRIPTION
**Pull request by fjodorver**
Save split user ids in database

### CODE REVIEW

**Comment by Valodim** [comment]
Looks good. However, this is missing a migration path from an old database format, and should also increase the db version.

**Comment by fjodorver** [comment]
pull request is updated?

**Comment by vershinin** [comment]
@Valodim, could you have a look?

**Comment by Valodim** [comment]
Merged this PR, if you want to do the other thing simply open a new one. Thanks! :+1:

**Pull request merged**
