### PR TITLE
Update ContactSyncAdapterService.java

### PR DESCRIPTION
**Pull request by advaita13**
Introduced a check in the requestContactsSync method to check if user has disabled automatic sync. If that is the case method will simply return and notification will be avoided.

Issue: https://github.com/open-keychain/open-keychain/issues/1720

### CODE REVIEW

**Comment by adithyaphilip** [comment]
Just a few pointers:
* Whenever you make a pull request, it might be helpful to link to the issue it solves (https://github.com/open-keychain/open-keychain/issues/1720). This helps keep track of which PR solves which issue, and also introduces a link to this PR in the linked issue.
* Doing a `rebase -i` and <a href="http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html">squashing</a> your commits into one helps keep the commit history of the OpenKeychain repo clean.

**Comment by advaita13** [comment]
Will keep that in mind. Thank you.

Is there some issue with Travis CI?

**Comment by adithyaphilip** [comment]
Could you squash the commits for this PR into one? You can push to the same branch after squashing with a `git push -f`.
And yes, there seems to be an issue with the Travis build, but probably not related to your changes.

**Comment by advaita13** [comment]
Merged and deleted the branch. Is it appearing as one single commit now?

**Comment by advaita13** [comment]
Got it all sorted now. Merged into 1 commit and opened up a pull request.

Issue: https://github.com/open-keychain/open-keychain/issues/1720
Pull: https://github.com/open-keychain/open-keychain/pull/1743

**Pull request closed without merging**
