### PR TITLE
Add visual element to verify the re-typed password. Refer #1357.

### PR DESCRIPTION
**Pull request by ishit**

### CODE REVIEW

**Comment by dschuermann** [comment]
Great idea.
Maybe we should use the same visuals as the ones used for the email text field for a unified experience ;)
I would also like to see this in it's own class similar to EmailEditText so I can also reuse this for https://github.com/open-keychain/open-keychain/issues/1382
Do you have time to do this?

**Comment by ishit** [comment]
Yes, how do you want the data to flow between PassphraseEdit and PassphraseEdiitAgain? Something like a BroadastManager? Also, shall I add another icons for this(copy of email text field icons) or reuse and rename the existing email text field icons?

**Comment by dschuermann** [comment]
* I see, the program flow would be too difficult. Then let's leave it integrated, don't put it in a new class.
Reuse
* Reuse and rename existing email text field icons

**Comment by ishit** [comment]
Done. 
rsz_device-2015-07-02-201036

**Comment by dschuermann** [comment]
Great work, much appreciated!

**Pull request merged**
