### PR TITLE
Fix Crash when no encryption subkey is available, Issue #1817

### PR DESCRIPTION
**Pull request by 007durgesh219**
screenshot_20160405-040401

### CODE REVIEW

**Comment by Valodim** [comment]
Looks good.

I'm a little confused about our own code right now though. @dschuermann Is there a  case where the sign encrypt operation *wouldn't* fail on missing encryption key ids?

**Comment by dschuermann** [comment]
@Valodim No there is no case. I think we can safely remove mFailOnMissingEncryptionKeyIds and the corresponding setters and getters and always fail on missing encryption keys

**Comment by dschuermann** [comment]
Ah and nice pull request @007durgesh219 !

**Comment by 007durgesh219** [comment]
Also, App will crash if we try to encrypt file using expried key. We should handle that too.

**Comment by dschuermann** [comment]
Hmm, now I am also confused: Shouldn't it be already impossible to select a key using the dropdown which is either revoked, expired or has no encryption subkeys?

**Comment by 007durgesh219** [comment]
No it's not enabled in dropdown but we can always go from home screen. From home screen select any expired key and press encrypt button on action bar.

**Comment by dschuermann** [comment]
It's not crashing for me with an expired key, but you are right using it is still possible.
We should also check for expired and revoked keys inside the encrypt activity, as it can also be called from outside of OpenKeychain with an Intent.
@007durgesh219 would you like to add this functionality to this pr?

**Comment by 007durgesh219** [comment]
Sure, I will add it

**Comment by dschuermann** [comment]
BTW thinking about this more: There should be no case where ``PgpSignEncryptOperation`` really crashes, it should always return with ``PgpSignEncryptResult(PgpSignEncryptResult.RESULT_ERROR, log);`` for wrong keys etc.
So if you encounter any case where it actually crashes, please report or make a pull request :)

**Comment by 007durgesh219** [comment]
I've updated PR please review it again

**Comment by dschuermann** [comment]
Great work, thanks!

**Pull request merged**
