### PR TITLE
redesign access and allowed secret key api dialogs

### PR DESCRIPTION
**Pull request by Valodim**
This PR redesigns the two api dialogs, from fullscreen into regular material yes/no style dialogs.

### CODE REVIEW

**Comment by Valodim** [comment]
screenshot_20170203-181510
screenshot_20170203-182434
screenshot_20170203-193219

scweenshots

**Comment by dschuermann** [comment]
Looks awesome!

I encountered one corner-case bug:

I encrypt a message to two public keys with the same email address "alice@example.com". "Alice" is a secret key, "Alice 2" is only a public key:
device-2017-02-07-204823

I asks for access to "Alice 2" but not for access to "Alice" (where we have the secret part):
device-2017-02-07-204850

**Comment by Valodim** [comment]
nice catch. should be fixed with the last commit

**Comment by dschuermann** [comment]
👍

**Pull request merged**
