### PR TITLE
WIP: Improve EncryptFilesFragment

### PR DESCRIPTION
**Pull request by runnerway**
We have some limitations in EncryptFilesFragment. Mainly:
- Saving of files not supported <= KitKat
- Saving of multiple files not supported
- No control on output filenames (useful when sharing with email..)

So, i spent some time to improve the situation by solving these problems.
This is a screenshot after this PR at this time (remember it's WIP)

screenshot_20160306-225101

Here we have the list of files we want to Encrypt.
If you tap on a file you get:

screenshot_20160306-225117

Here you can set the filename of the output file. (Probably we can add other file specific options..)
This filename will be used for saving and share actions.

If you tap the save icon in the action bar you get a folder picker to set the path where you want to place the output files. Now i'm using a library for the folder picker because i wanted to share a more or less completed idea in the shortest time to get feedback. But the plan is to write an own folder picker, specific for our use case.

This PR is a WIP because code needs a bit of clean up, some checks are needed, UI need to be improved, bugs need to be fixed, granting of storage permission, i need to write a proper folder picker, i will add gestures etc..
But i wanted to start sharing this work to hear your opinions.
Do you like this idea? Do you have any suggestions before i go deep on this way?

I think all these things are pretty useful.

### CODE REVIEW

**Comment by dschuermann** [comment]
Hey, thanks for your work on this and your other awesome pull requests.
Unfortunately, I don't like to introduce an implementation of a save dialog again. Not by us or by an external dependency. We had some security issues due to these in the past (see https://github.com/open-keychain/open-keychain/wiki/cure53-Security-Audit-2015), I suspect that we easily make new vulnerabilities by implementing this again. IMHO it's okay to leave this feature out for users below Kitkat.

What I'd like to see is a possibility of saving multiple encrypted files using http://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT_TREE . See https://github.com/open-keychain/open-keychain/issues/1599 for a previous discussion. Currently I would propose saving all encrypted files separately and not in a dedicated zip archive (as discussed in the issue).

**Comment by runnerway** [comment]
Oh sorry. I've missed that discussion. 

Tommorrow I will edit this PR introducing ACTION_OPEN_DOCUMENT_TREE and remove the external dependency. 
Then in next days I will clean up code and setup a good UI until we are satisfied.  

Yes. In this PR encrypted files are already saved separately.

**Comment by runnerway** [comment]
I tried using ACTION_OPEN_DOCUMENT_TREE and it works very well. 
Doing so will also solves other problems.

I'm waiting for my other PR https://github.com/open-keychain/open-keychain/pull/1771 to be finished and merged before pushing the latest version of this PR. 

After that, i will return on this PR to finish this work too.
In this way i will to be able to produce good and robust code.

**Comment by dschuermann** [comment]
Hey @runnerway 
If you are still interested in contributing to OpenKeychain, it would be great to see new progress on this pull request. If not please tell me.

**Comment by Valodim** [comment]
closing stale PR

**Pull request closed without merging**
