### PR TITLE
Fix Dark theme no longer works in main screen on android 5, Issue#1746

### PR DESCRIPTION
**Pull request by 007durgesh219**

### CODE REVIEW

**Comment by dschuermann** [comment]
Have you tested this on all supported versions of OpenKeychain?

**Comment by 007durgesh219** [comment]
No I only tested on android 5.  Will do that

**Comment by 007durgesh219** [comment]
@dschuermann I tested for all android version in the emulator (API 16,17,18,19,21,23) it's working.

**Comment by dschuermann** [comment]
15 is missing ;)

**Comment by 007durgesh219** [comment]
OK sure checking for that also

**Comment by 007durgesh219** [comment]
Tested for API 15 too. It's working.

**Comment by dschuermann** [comment]
Great thanks

**Pull request merged**
