### PR TITLE
Fix CertifyKeyActivity back button on action bar not working #1758

### PR DESCRIPTION
**Pull request by 007durgesh219**

### CODE REVIEW

**Comment by 007durgesh219** [comment]
@dschuermann I think it will be better to handle the home menu item click in BaseActivity. To avoid those small mistakes in future. Should I do that??

**Comment by Valodim** [comment]
Sounds good to me.

**Comment by 007durgesh219** [comment]
I've updated PR. Now it will handle home click in BaseActivity

**Comment by opg7371** [comment]
@Valodim is this issue still open...??

**Comment by Valodim** [comment]
needed to rebase for testing, and pushed from there. thanks :+1:

**Pull request closed without merging**
