### PR TITLE
multi decrypt

### PR DESCRIPTION
**Pull request by Valodim**
don't merge yet, work in progress. this is a follow-up to #1297.

this has become sort of a larger project than I expected, keeping this pull request around to track progress.

- [x] CachingDataDecryptorFactory, get rid of RuntimeException based control flow and allow caching of session keys
- [x] DecryptVerifyResult now includes a CryptoInputParcel which can be used to reproduce its results without further user input
- [x] split up decryptfilesfragment into input and listing
- [x] decrypted files are listed in the new fragment rather than just saved/shared
- [x] display encryption and signature status individually
- [x] icon displayed for mime-type
- [x] OpenPgpMetadata includes accurate filesize - this is not working completely for the metadata-only call yet! (not fixed, but no longer relevant because I don't use this call anymore)

todos:
- [x] backend: support using cached session keys for non-divert-to-card keys (obsolete)
- [x] cache decrypted data for send intent
- [ ] properly handle unknown signatures (requires re-decryption!)
- [x] options in file context menu (view log, save to file, delete encrypted file)

for later:
- multi-select
- uri read permission handling

### CODE REVIEW

**Comment by Valodim** [comment]
current wip screenshot

**Comment by Valodim** [comment]
- move to card layout
- drop "decrypt metadata" step. we need to decrypt to verify the signature anyways, might as well save the result and re-use it later

**Comment by Valodim** [comment]
rebased on instrumentation branch (and thus recent master)

**Comment by Valodim** [comment]
tons of progress!

- single pass decryption, cache decrypted data (way easier data flow, but might be up for debate)
- prefer temporary storage provider over data in parcels for most operations
- unified clipboard handling: decrypt from clipboard as from file, encrypt to clipboard stores URIs which are resolved in-time
- got rid of api < 11 clipboard compatibility layer
- thumbnails for decryted data

**Comment by Valodim** [comment]
ah yeah, build fails because some of the public intents moved around. need to discuss how to handle these changes... are there apps which rely on DecryptTextActivity behavior?

**Comment by dschuermann** [comment]
@Valodim I don't know of any published apps that rely on this behaviour. But if you change this, please update the wiki and the demo app at https://github.com/open-keychain/openkeychain-intents

**Comment by Valodim** [comment]
- saving done & tested
- deletion done & tested
- preferences tested
- switched to indeterminate progress
- open file logic moved to encryptdecryptoverviewfragment

**Pull request merged**
