### PR TITLE
Fix travis android-24 dep

### PR DESCRIPTION
**Pull request by nmikhailov**

### CODE REVIEW

**Comment by nmikhailov** [comment]
@dschuermann i remember that we specifically used openjdk instead of oracle, why was that the case?

**Comment by nmikhailov** [comment]
Problem is that there is no openjdk8 on travis https://docs.travis-ci.com/user/languages/java/
Java8 is required by android-24

**Comment by dschuermann** [comment]
I think OpenJDK was required to compile Bouncy Castle and get it to working as a JCA provider without signing it with a vendor key.

**Comment by Valodim** [comment]
Indeed. The JCA implementation in Oracle JDK does not allow for unsigned JCA providers, so for the unit tests to work there is no way to use that as long as we patch anything in BouncyCastle

**Comment by dschuermann** [comment]
I commented on one of there issues (https://github.com/travis-ci/travis-ci/issues/2968) but I there are many issues related to OpenJDK open on their issue tracker.

**Comment by nmikhailov** [comment]
It works now.
Used openjdk8 from ppa, seems like its the only option now.

**Comment by dschuermann** [comment]
Awesome!

**Pull request merged**
