### PR TITLE
Passphrase wizard + PIN Passphrase support

### PR DESCRIPTION
**Pull request by Hiperzone**
First Passphrase Wizard code review. There are still a few code changes that I need to implement. Also expect further changes down the line in terms of code cleanup and bug fixes.

### CODE REVIEW

**Comment by Valodim** [comment]
some files don't have 4 spaces indentation, particularly PgpKeyOperation was reformatted

**Comment by dschuermann** [comment]
Please squash the commits so that the code style changes don't appear in git history.

**Comment by dschuermann** [comment]
Please also add license headers

**Comment by dschuermann** [comment]
Please squash the commit e8b08b3 with the ones before. The code style changes shouldn't appear in history.

**Comment by Valodim** [comment]
finally got to look it over! so sorry for the delay~

- the pin input gives no feedback on the number of digits entered or whether a button press was successful, this is very confusing
- we should have a minimum and maximum pin length
- pin entry dialog: oversized on tablets
- pin entry dialog: keyboard pops up in background
- pin entry dialog: back button doesn't work
- button color is green? (was this different before?)

as mentioned above, please squash the indentation-commit with its fix, to get a cleaner git history in this regard.

**Comment by dschuermann** [comment]
:( Still not squashed

**Comment by Hiperzone** [comment]
Don't worry, I will squash them soonish :). GitHub updates the pull request each time I do a push. So the next time I do a push, everything should be squashed. Just need to finish some fixes and do some cleanup.

**Comment by Hiperzone** [comment]
-squash done, will apply Valodim suggestions today and do a merge

**Comment by dschuermann** [comment]
@Hiperzone Somehow we talk past each other :/ I still don't see the desired squash.

To be more precise: I see tabs in the first commit that introduces most of your changes: https://github.com/Hiperzone/open-keychain/commit/303af230b417d02edd38984cfb4c7f9775508ac7 . I don't like to have such a huge commit in history that is followed by another huge commit that just fixes tabs to whitespaces (https://github.com/Hiperzone/open-keychain/commit/1487f7514ae42a53494730917379832f965cc1d0).

Do you have problems with using git squashing?, if yes, please explain what problems you have :)

**Comment by Hiperzone** [comment]
:( I think i misunderstood something. I decided to squash the last commits because they were followed by tab fixing commit which you did not want to be a single commit. Sadly I cannot go back now because I lost all the previous history.
The first commit was huge because i could not merge the code and had to move all my code to the most recent version of OpenKeyChain.

Do you want me to squash the two commits together? Hopefully I did not miss any tabs.

**Comment by dschuermann** [comment]
@Hiperzone Yes please squash the commits together. The goal should be that there are no tabs in any commits :)

**Comment by Hiperzone** [comment]
Done

**Comment by dschuermann** [comment]
@Hiperzone I wanna see a progress on this pr, are you working on Valodims items?

**Comment by Hiperzone** [comment]
Yes, I also finished pattern unlocking

**Comment by Hiperzone** [comment]
Integrated the pattern passpgrase into the wizard repository.

**Comment by dschuermann** [comment]
@Hiperzone Please rebase and fix all missing todos, then ping me, so we can get this into master!

**Comment by Hiperzone** [comment]
Working hard on it, I'm doing my best at the moment to get this done for tomorrow meeting.

**Comment by dschuermann** [comment]
I really hoped that we can get this reviewed _before_ the meeting. Now, we can not provide much feedback at the meeting, because it's not done.

**Comment by dschuermann** [comment]
Closing, because of https://github.com/open-keychain/open-keychain/pull/1481

**Pull request closed without merging**
