### PR TITLE
Orange toolbar for certify and fingerprint activity added

### PR DESCRIPTION
**Pull request by ishan1604**

### CODE REVIEW

**Comment by dschuermann** [comment]
This can be done in xml, no need to do it in-code.
Look into the included toolbar layout.

**Comment by ishan1604** [comment]
I saw that. I did that using the code in java because if I make the changes
in the xml of the included toolbar to orange color, won't it reflect on all
the activities where it is referred to?

Or should I create a separate XML file for the orange toolbar and include
that there ?

Please advise, Thanks. :)

**Comment by dschuermann** [comment]
Create a copy of the toolbar xml with an orange color and include it.

**Comment by ishan1604** [comment]
Sent a new pull request with your suggested changes. Thanks for your advise

**Pull request closed without merging**
