### PR TITLE
Github action CI

### PR DESCRIPTION
**Pull request by hannesa2**
Please verify your repo settings concerning actions.
My fork runs, but with errors on current master https://github.com/hannesa2/open-keychain/pull/1

When you merge #2553, I will rebase this PR

### CODE REVIEW

**Comment by Valodim** [comment]
Just a heads-up, this was implicitly closed by merging #2553 because that's the PR base

**Comment by hannesa2** [comment]
No I rebased it, but reopen is your issue

**Comment by Valodim** [comment]
you'll need to change the base branch, too. github won't let me reopen a pr that's based on a closed pr :)

**Comment by hannesa2** [comment]
And I can't change base on a closed PR
image

I'll make a new one

**Comment by Valodim** [comment]
Haha. softlocked on github ;)

**Comment by hannesa2** [comment]
But the first finding is an issue with gradle.jar

image

Please see https://github.com/hannesa2/open-keychain/pull/1/checks?check_run_id=724657511

**Comment by hannesa2** [comment]
You have to enable Github actions !

image

**Comment by Valodim** [comment]
I'm aware, but we'll need @dschuermann to do that. I'll ping him about it.

**Pull request closed without merging**
