### PR TITLE
Resize QR code properly in landscape orientation

### LINKED ISSUE #1644: QR Code fullscreen: landscape broken
QR Code is not properly resized in fullscreen.

### PR DESCRIPTION
**Pull request by unyoungwax**
Fixes #1644

`AspectRatioImageView` is removed because it is no longer used.

### CODE REVIEW

**Comment by dschuermann** [comment]
Habe you tested this in oder Android Version? You can Start an Emulator and rotate it to test (http://stackoverflow.com/questions/4535298/how-to-rotate-the-android-emulator-display).

**Comment by unyoungwax** [comment]
Yes, I have tested on Android 4.1 and above (Jelly Bean, KitKat, Lollipop and Marshmallow).

**Comment by dschuermann** [comment]
great, tested it and works!

**Comment by Valodim** [comment]
+3/-151 lines and it strictly improves stuff. best kind of patch. :+1:

**Pull request merged**
