### PR TITLE
Fix for "Delete after encryption" Issue #1116

### PR DESCRIPTION
**Pull request by manojkhannakm**

### CODE REVIEW

**Comment by dschuermann** [comment]
This is only a small part of the issue #1116, please read it carefully. Also please rebase.

**Comment by manojkhannakm** [comment]
I think I've fixed everything that you've mentioned.

> * If the user chooses to encrypt a file and share it, the dialog is shown behind the share menu of Android, thus the file will never be deleted.

To fix this I've created a callback class OnDeletedListener to listen if the files are getting deleted and then starting the Share activity.

> * If multiple files are encrypted the dialog is shown for every file separately, also the files are deleted separately.

For this I've made the DeleteFileDialogFragment class accept multiple uris as varargs so as to delete multiple files.

> * Show dialog before sharing the encrypted temporary file and only proceed to sharing if "Delete" is clicked
* Execute deletion after encryption process succeeded
* Allow deletion of multiple files, i.e. show a list of files in the DeleteFileDialogFragment dialog. Also show a list of files in the Toasts, collect files that failed to delete.

And the above fixes are completely based on the flow which you've stated above.

If I'm still missing out something, please let me now.

**Comment by dschuermann** [comment]
@manojkhannakm I annotated the line.

**Comment by manojkhannakm** [comment]
My bad, thanks for pointing that out.

Also while testing I've found a bug. When selecting files for encryption, if a same file is selected multiple times while deleting it causes a crash, this is because the second time it tries to delete the file it is not found. Should this be handled while selecting the files(like restricting selection of same file) or while deleting(removing duplicate uri).

**Comment by dschuermann** [comment]
Yes I think this should be handled when selecting the file. Simply don't allow the selection of the same file again. We should also catch the problem in the deletion code and handle it like a file that could not be deleted.

**Comment by manojkhannakm** [comment]
Ok. So how should the users be warned when they add duplicate files, a toast or using the Notify class.

**Comment by dschuermann** [comment]
I would prefer the Notify class.

**Comment by manojkhannakm** [comment]
Updated pull request https://github.com/open-keychain/open-keychain/pull/1136

**Pull request closed without merging**
